/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chengang_myapplication_MainActivity */

#ifndef _Included_com_example_chengang_myapplication_MainActivity
#define _Included_com_example_chengang_myapplication_MainActivity

JNIEXPORT jstring JNICALL Java_com_example_chengang_myapplication_MainActivity_getStringFromNative
  (JNIEnv *, jobject, jstring, jstring);

#endif
